import { foods, NewFood } from '@/infrastructure/db/schema/foods';
import { DBTransaction } from '@/types/db';

import { Mood, MOOD_LIST } from '@/common/constants/foods.constants';

const FOOD_DATA: Record<Mood, string[]> = {
  happy: [
    'Chocolate Chip Cookies',
    'Mango Smoothie',
    'Lemon Ricotta Pancakes',
    'Rainbow Sherbet',
    'Caramel Popcorn',
    'Cheesecake Slice',
    'Hazelnut Gelato',
    'Red Velvet Cupcake',
    'Waffles with Berries',
    'Mint Chocolate Ice Cream',
    'Apple Crumble',
    'Key Lime Pie',
    'Jelly Donuts',
    'Cinnamon Rolls',
    'Pecan Pie',
    'Fudge Brownies',
    'Cotton Candy',
    'Salted Caramel Milkshake',
    'Churro with Chocolate Sauce',
    "S'mores Bar",
    'Bubble Tea (Taro)',
    'Rice Krispie Treats',
    'Boston Cream Pie',
    'Chocolate Lava Cake',
    'Banana Split',
    'Frozen Yogurt with Toppings',
    'Macarons (Assorted)',
    'Strawberry Shortcake',
    'Beignets',
    'Gummy Bears',
    'Birthday Cake Ice Cream',
    'Pineapple Upside Down Cake',
    'Snickerdoodle Cookies',
    'Pain au Chocolat',
    'Tres Leches Cake',
    'Pound Cake with Glaze',
    'Oreo Milkshake',
    'Chocolate Dipped Strawberries',
    'Tiramisu',
    'Baklava',
    'Cannoli',
    'Mocha Frappuccino',
    'Peanut Butter Cups',
    'Carrot Cake',
    'Cream Puff',
    'Gingerbread Cookies',
    'Lemon Bars',
    'Chocolate Mousse',
    'Waffle Cone Ice Cream',
    'Hot Fudge Sundae',
    'Affogato',
    'Creme Brulee Cheesecake',
    'Nougat Candy',
    'Butterscotch Pudding',
    'Chocoflan',
    'Funnel Cake',
    'Pralines',
    'Cookie Dough Ice Cream',
    'White Chocolate Raspberry Scone',
    'Maple Pecan Danish',
    'Tootsie Rolls',
    'Almond Biscotti',
    'Espresso Brownie',
    'Pistachio Ice Cream',
    'Angel Food Cake',
    'Orange Creamsicle',
    'Taffy',
    'Chocolate Milk',
    'Malt Ball Candy',
    'Dulce de Leche',
    'Gourmet Burger',
    'Soft Pretzel',
    'Sushi Rolls',
    'Crispy Chicken Tacos',
    'Bacon & Eggs',
    'Butter Chicken',
    'Spicy Tuna Bowl',
    'Margherita Pizza',
    'Fish and Chips',
    'BBQ Pulled Pork Sandwich',
    'Chicken Wings (Honey Garlic)',
    'Grilled Cheese and Tomato Soup',
    'Loaded Nachos',
    'Reuben Sandwich',
    'Shrimp Scampi',
    'Philly Cheesesteak',
    'Poutine',
    'Pad Thai',
    'Beef Stroganoff',
    'Chili Dog',
    'Mashed Potatoes with Gravy',
    'Fajitas (Steak)',
    'Tater Tots',
    'Chicken Pot Pie',
    'Lasagna',
    'Meatball Sub',
    "Shepherd's Pie",
    'Jalapeño Poppers',
    'Ramen (Spicy Miso)',
    'Chicken and Waffles',
    'Cuban Sandwich',
    "General Tso's Chicken",
    'Hot Dog with Mustard',
    'Macaroni and Cheese',
    'Quesadilla (Chicken)',
    'Stuffed Bell Peppers',
    'Chicken Tikka Masala',
    'Goulash',
    'Pierogi (Potato & Cheese)',
    'Spaghetti Carbonara',
    'Arancini',
    'Croque Monsieur',
    'Tuna Melt',
    'Gumbo',
    'Muffuletta',
    'Fried Chicken Sandwich',
    'Chowder (Clam)',
    'Taco Salad',
    'Chicken Parmigiana',
    'Bratwurst with Sauerkraut',
    'Chicken Enchiladas',
    'Vietnamese Pho',
    'Corn Dog',
    'Pot Roast',
    'Samosas',
    'Bacon Cheeseburger',
    'Empanadas (Beef)',
    'Jambalaya',
    'French Onion Soup',
    'Calzone',
    'Gyros',
    'Pork Buns (Bao)',
    'Chicken Fajita Bowl',
    'Curry (Thai Green)',
    'New England Clam Bake',
    'Kolaches',
    'Scotch Egg',
    'Sloppy Joe',
    'Paella Mixta',
    'Chiles en Nogada',
    'Fresh Strawberry Salad',
    'Avocado Toast',
    'Fruit Pizza',
    'Caesar Salad',
    'Greek Yogurt with Honey',
    'Iced Matcha Latte',
    'Caprese Salad',
    'Gazpacho',
    'Watermelon Slices',
    'Açai Bowl',
    'Bruschetta',
    'Pomegranate Juice',
    'Vegetable Spring Rolls',
    'Lemonade (Freshly Squeezed)',
    'Smoothie Bowl (Green)',
    'Cantaloupe with Prosciutto',
    'Cucumber Sandwiches',
    'Cobb Salad',
    'Tabbouleh',
    'Hummus and Pita',
    'Blackberry Tart',
    'Kiwi Slices',
    'Fresh Berry Parfait',
    'Cold Brew Coffee',
    'Bell Pepper Strips with Dip',
    'Chicken Salad Sandwich (Light)',
    'Honeydew Melon',
    'Orange Slices with Mint',
    'Shrimp Cocktail',
    'Spinach and Feta Quiche',
    'Vietnamese Summer Rolls',
    'Arugula Salad with Lemon Vinaigrette',
    'Tomato Basil Soup (Cold)',
    'Pico de Gallo',
    'Ceviche',
    'Grilled Peach Salad',
    'Mint Julep (Non-Alcoholic)',
    'Rainbow Fruit Skewers',
    'Zucchini Noodles with Pesto',
    'Gazpacho Verde',
    'Mango Sticky Rice',
    'Grapefruit Juice',
    'Blistered Shishito Peppers',
    'Fattoush Salad',
    'Pineapple Salsa',
    'Watermelon & Feta Salad',
    'Lassi (Sweet)',
    'Edamame Salad',
    'Cucumber Gazpacho',
    'Vegetable Korma',
    'Coconut Water',
    'Black Bean Salad',
    'Mojito (Virgin)',
    'Grilled Halloumi Salad',
    'Cold Soba Noodles',
    'Apple Slices with Peanut Butter',
    'Smoothie (Turmeric & Ginger)',
    'Watercress Soup',
    'Mango and Lime Salad',
    'Açaí Berries',
    'Elotes (Mexican Street Corn)',
    'Takoyaki (Japanese Octopus Balls)',
    'Churros',
    'Arepas',
    'Baozi (Steamed Buns)',
    'Satay Chicken Skewers',
    'Falafel Wrap',
    'Gyoza (Pork)',
    'Supa de Pollo (Chicken Soup)',
    'Tostones',
    'Biltong',
    'Pretzel Bites',
    'Spring Rolls (Fried)',
    'Currywurst',
    'Taco al Pastor',
    'Pani Puri',
    'Kebab (Doner)',
    'Lumpia (Filipino Spring Rolls)',
    'Pinchos',
    'Supplì (Fried Rice Balls)',
    'Vada Pav',
    'Köttbullar (Swedish Meatballs)',
    'Mochi',
    'Chana Masala',
    'Aloo Tikki',
    'Chimichanga',
    'Borek (Spinach & Cheese)',
    'Pupusas',
    'Khao Soi',
    'Arepa de Huevo',
    'Okonomiyaki',
    'Msemen',
    'Bánh Mì',
    'Pastel de Choclo',
    'Spanakopita',
    'Coxinha',
    'Khachapuri',
    'Tostada',
    'Souvlaki (Chicken)',
    'Fish Ball Skewers',
    'Queso Fundido',
    'Zha Jiang Mian',
    'Sfiha',
    'Churro Waffle',
    'Kulfi',
    'Gỏi Cuốn (Shrimp Summer Rolls)',
    'Kimchi Pancake',
    'Hushpuppies',
    'Dosa',
    'Bakkwa',
  ],

  stressed: [
    'Warm Oatmeal',
    'Lentil Soup',
    'Whole Grain Pasta',
    'Turkey Sandwich',
    'Chamomile Tea',
    'Chicken Noodle Soup',
    'Banana Nut Bread',
    'Grilled Cheese and Soup',
    'Mashed Avocado on Toast',
    'Steamed White Rice',
    'Mug Cake (Microwave)',
    'Plain Yogurt with Berries',
    'Scrambled Eggs (Soft)',
    'Hot Cocoa (Dark)',
    'Cream of Mushroom Soup',
    'Rice Pudding',
    'Pudding (Vanilla)',
    'Apple Sauce',
    'Soft Boiled Egg',
    'Toast with Butter',
    'Congee (Rice Porridge)',
    'Tomato Soup (Creamy)',
    'Cheese and Crackers',
    'Canned Peaches',
    'Simple Broth',
    'Cream of Wheat',
    'Instant Noodles (Plain)',
    'Cereal (Unsweetened)',
    'Plain Bagel',
    'Biscuits and Gravy',
    'Baked Potato with Sour Cream',
    'Peanut Butter Toast',
    'Milk and Cookies (Plain)',
    'Buttered Noodles',
    'Malt-O-Meal',
    'English Muffin with Jam',
    'Sourdough Bread',
    'Wonton Soup',
    'Pasta with Marinara Sauce',
    'Soft Taco (Ground Beef)',
    'Mild Chicken Curry',
    'Oatmeal Raisin Cookies',
    'Canned Tuna Salad',
    'Vegetable Broth',
    'Soft Pretzels with Salt',
    'Milk Toast',
    'Zwieback',
    'Steamed Veggies',
    'Plain Potato Chips',
    'Crackers with Cheese Spread',
    'Rice Cakes',
    'Hot Cereal (Grits)',
    'Plain Pancakes',
    'Tapioca Pudding',
    'Rice and Beans (Simple)',
    'Sopa de Fideo',
    'Dry Cereal Snack',
    'Graham Crackers',
    'Plain Pita Bread',
    'Frozen Waffles',
    'Macaroni Salad',
    'Soft Rolls',
    'Boiled Chicken',
    'Plain Scones',
    'Baked Sweet Potato (Plain)',
    'Hard Cider (Non-Alcoholic)',
    'Water Biscuits',
    'Buttermilk',
    'Rice Flour Porridge',
    'Dark Chocolate Bar (85%)',
    'Almonds & Walnuts Mix',
    'Steamed Spinach',
    'Miso Soup',
    'Avocado Oil Salad',
    'Sweet Potato Fries',
    'Kombucha Drink',
    'Tofu Stir Fry',
    'Oyster Shooters',
    'Mackerel Fillets',
    'Flaxseed Crackers',
    'Chia Seed Pudding',
    'Pumpkin Seeds (Roasted)',
    'Cashews',
    'Black Beans',
    'Broccoli (Steamed)',
    'Quinoa Salad',
    'Sardines in Olive Oil',
    'Soy Milk',
    'Swiss Chard',
    'Magnesium Supplement Drink',
    'Spinach and Kale Smoothie',
    'Yogurt (Kefir)',
    'Sesame Seeds',
    'Brown Rice (Long Grain)',
    'Lentils (Cooked)',
    'Brazil Nuts',
    'Sun Dried Tomatoes',
    'Cacao Nibs',
    'Wheat Germ',
    'Whole Wheat Bread',
    'Black Sesame Soup',
    'Nutritional Yeast',
    'Artichoke Hearts',
    'Oat Milk Latte',
    'Seaweed Snacks',
    'Green Beans',
    'Hemp Seeds',
    'Beet Greens',
    'Tofu Scramble',
    'Chickpea Curry (Mild)',
    'Black Eyed Peas',
    'Spinach Pesto Pasta',
    'Green Juice (Celery, Cucumber)',
    'Hazelnuts',
    'Bok Choy',
    'Tahini Dip',
    'Sunflower Seeds',
    'Farro',
    'Buckwheat Porridge',
    'Tempeh Stir Fry',
    'Almond Butter',
    'Black Olives',
    'Spirulina Smoothie',
    'Amaranth Porridge',
    'Millet',
    'Watermelon Seeds',
    'Black Tea (Decaf)',
    'Fenugreek Seeds',
    'Hard-Boiled Eggs',
    'Roasted Chickpeas',
    'Cottage Cheese',
    'Peanut Butter Smoothie',
    'Black Beans and Rice',
    'Kimchi Fried Rice',
    'Pesto Spaghetti',
    'Chicken Fried Rice',
    'Veggie Burger',
    'Turkey Meatloaf',
    'Shrimp and Grits',
    'Spicy Ramen',
    'Curry Puff',
    'Pickles (Dill)',
    'Ginger Ale',
    'Hot and Sour Soup',
    'Spicy Miso Soup',
    'Wasabi Peas',
    'Jerk Chicken',
    'Buffalo Chicken Dip',
    'Salsa and Chips',
    'Chai Latte (Spicy)',
    'Spicy Tuna Roll',
    'Gochujang Tofu',
    'Jalapeño Cheddar Bread',
    'Hot Cheetos',
    'Sour Candy (Extreme)',
    'Spicy Peanut Noodles',
    'Red Pepper Flakes on Pizza',
    'Chipotle Chicken Bowl',
    'Spicy Margarita (Virgin)',
    'Sichuan Dan Dan Noodles',
    'Kimchi Stew (Kimchi Jjigae)',
    'Vindaloo (Mild Chicken)',
    'Spicy Sriracha Snack Mix',
    'Chilli con Carne',
    'Habanero Salsa',
    'Spicy Mango Salad',
    'Peri-Peri Chicken',
    'Tabasco Sauce on Eggs',
    'Black Pepper Crackers',
    'Curried Deviled Eggs',
    'Spicy Pickled Asparagus',
    'Aglio e Olio Pasta (Spicy)',
    'Hot Sauce on Popcorn',
    'Mala Hot Pot (Mild)',
    'Spicy Edamame',
    'Chili Oil Noodles',
    'Ghost Pepper Pretzels',
    'Spicy Guacamole',
    'Fire Cider Shot',
    'Mustard Greens',
    'Horseradish Mash',
    'Spicy V8 Juice',
    'Cajun Shrimp Boil',
    'Spicy Black Bean Soup',
    'Wasabi Mayonnaise',
    'Spicy Noodle Soup',
    'Pickled Ginger',
    'Cucumber Water',
    'Coconut Yogurt',
    'Watermelon Juice',
    'Herbal Infusion (Peppermint)',
    'Fresh Fruit Popsicle',
    'Iced Tea (Unsweetened)',
    'Grapefruit Segments',
    'Celery Sticks',
    'Carrots and Hummus',
    'Cold Soup (Borscht)',
    'Aloe Vera Drink',
    'Frozen Grapes',
    'Jicama Slices',
    'Kefir Water',
    'Mineral Water (Sparkling)',
    'Orange Juice (Fresh)',
    'Salad with Olive Oil',
    'Smoothie (Electrolyte)',
    'Zucchini Sticks',
    'Cold Glass of Milk',
    'Fruit Salad (Citrus)',
    'Hydrating Broth',
    'Lemon and Ginger Water',
    'Rice Milk',
    'Sauerkraut Juice',
    'Spicy V8',
    'Vegetable Juice (Low Sodium)',
    'Water with Mint and Lime',
    'Honeydew Melon Smoothie',
    'Beet Juice',
    'Cranberry Juice',
    'Fresh Limeade',
    'Tomato Slices with Salt',
    'Fizzy Water with Lemon',
    'Low-Sodium Bouillon',
    'Pear Slices',
    'Unsweetened Almond Milk',
    'Apple Cider Vinegar Drink',
    'Cold Green Tea',
    'Frozen Blueberries',
    'Pomegranate Juice (Diluted)',
    'Smoothie (Peach & Kale)',
    'Tomato and Cucumber Salad',
    'Watermelon Gazpacho',
    'Whey Protein Shake',
    'Carrot Juice',
    'Fennel Bulb Slices',
    'Iced Hibiscus Tea',
    'Nopal Juice',
    'Rooibos Tea',
    'Smoothie (Banana & Spinach)',
    'Soy Milk (Plain)',
    'Water with Cucumber',
    'Cold Brew Decaf',
    'Apple Juice (Unfiltered)',
    'Lemon-Honey Water (Warm)',
    'Plum Slices',
    'Rye Crackers',
    'Sea Salt Crackers',
  ],

  tired: [
    'Salmon with Quinoa',
    'Spinach Omelette',
    'Lean Beef Steak',
    'Energy Bar',
    'Tuna Salad',
    'Fortified Cereal',
    'Pork Chops',
    'Chicken Shawarma',
    'Sweet Potato Hash',
    'Black Forest Ham',
    'Edamame Pods',
    'Whole Wheat Toast',
    'Cottage Cheese and Pineapple',
    'Hard-Boiled Egg Whites',
    'Protein Shake (Whey)',
    'Turkey Jerky',
    'Chicken Breast (Grilled)',
    'Lentil Soup',
    'Greek Yogurt (High Protein)',
    'Nut Butter on Celery',
    'Beef Liver',
    'Venison Steak',
    'Lamb Chops',
    'Cod Fillet (Baked)',
    'Halibut (Pan-Seared)',
    'Scallops (Seared)',
    'Shrimp (Boiled)',
    'Trout (Grilled)',
    'Buffalo Meat (Lean)',
    'Pork Tenderloin',
    'Soy Nuts',
    'Mussel Meats',
    'High-Protein Cottage Cheese',
    'Egg Salad Sandwich',
    'Sockeye Salmon',
    'Chicken Sausage',
    'Seitan Strips',
    'High-Protein Pancakes',
    'Ricotta Cheese (Skim)',
    'Fish Roe',
    'Quail Eggs',
    'Goat Meat (Stewed)',
    'Turkey Bacon',
    'Dry Roasted Peanuts',
    'Pea Protein Powder',
    'Hemp Protein Bar',
    'Kielbasa (Lean)',
    'Ham Steak',
    'Veal Cutlet',
    'Bison Burger',
    'Pâté (Liver)',
    'Wild Rice Pilaf',
    'Flank Steak',
    'Smoked Salmon Bagel',
    'Tofu Satay',
    'Beef Ribs (Short)',
    'Chicken Thigh (Skinless)',
    'Sausage Patties (Turkey)',
    'White Fish Tacos',
    'Sprouted Grain Bread',
    'Chicken Burrito Bowl',
    'Protein Waffles',
    'Kangaroo Meat',
    'Duck Breast',
    'Marrow Bones (Broth)',
    'Chorizo (Lean)',
    'Sardines (Canned)',
    'Tripe Soup',
    'Goose Meat',
    'Brown Rice Bowl',
    'Blueberry Muffins',
    'Orange Juice',
    'Cranberry Scones',
    'Broccoli Cheddar Soup',
    'Veggie Wrap',
    'Bran Muffin',
    'Grapefruit Segments',
    'Sweet Potato Fries',
    'Oatmeal with Honey',
    'Whole Wheat Pasta',
    'Banana (Ripe)',
    'Whole Grain Bagel',
    'Kidney Beans',
    'Butternut Squash Soup',
    'Acorn Squash (Baked)',
    'Pumpernickel Bread',
    'Oat Bran',
    'Millet Porridge',
    'Barley Soup',
    'Rye Bread',
    'Red Grapes',
    'Pear (Unpeeled)',
    'Whole Wheat Pita',
    'Brussels Sprouts (Roasted)',
    'Collard Greens',
    'Kale Salad (Massaged)',
    'Asparagus (Steamed)',
    'Winter Squash',
    'Sweet Corn',
    'Baked Apple',
    'Mango (Fresh)',
    'Kiwi (Fresh)',
    'Papaya (Fresh)',
    'Pineapple (Fresh)',
    'Pomegranate Seeds',
    'Red Bell Peppers',
    'Butternut Squash',
    'Beets (Roasted)',
    'Apricots (Dried)',
    'Prunes',
    'Raisins',
    'Sweet Potato (Mashed)',
    'Oat Crackers',
    'Quinoa Salad with Veggies',
    'Air-Popped Popcorn',
    'Multi-Grain Cereal',
    'Blackberries',
    'Raspberries',
    'Strawberries',
    'Honeydew Melon',
    'Cantaloupe',
    'Tangerine',
    'Avocado (Slices)',
    'Tomato (Roma)',
    'Cucumber (Slices)',
    'Cabbage (Shredded)',
    'Mushrooms (Sautéed)',
    'Cauliflower (Roasted)',
    'Zucchini (Grilled)',
    'Broccoli Rabe',
    'Jicama Sticks',
    'Celery and Peanut Butter',
    'Baked Plantains',
    'Whole Grain Tortilla',
    'Bulgur Wheat',
    'Freekeh',
    'Taro Root',
    'Yams',
    'Salsify',
    'Parsnips (Roasted)',
    'Rutabaga',
    'Turnips',
    'Kohlrabi',
    'Water Chestnuts',
    'Jujube Fruit',
    'Persimmon',
    'Guava',
    'Star Fruit',
    'Coffee (Black)',
    'Green Tea',
    'Ginger Shot',
    'Iced Coffee (No Sugar)',
    'Yerba Mate',
    'Matcha Tea (Hot)',
    'Espresso Shot',
    'Black Tea (Strong)',
    'Cold Brew Concentrate',
    'Lemon Water (Chilled)',
    'V8 Energy Drink',
    'Ginseng Tea',
    'Smoothie (Spinach & Banana)',
    'Sparkling Water (Plain)',
    'Pu-erh Tea',
    'Oolong Tea',
    'Peppermint Tea',
    'Chai Tea (Unsweetened)',
    'Kombucha (Ginger)',
    'Electrolyte Drink (Sugar-Free)',
    'Wheatgrass Shot',
    'Turmeric Latte (No Sugar)',
    'Coconut Water',
    'Grapefruit Juice (Unsweetened)',
    'Apple Cider Vinegar Shot',
    'Beetroot Juice',
    'Water with Lemon and Cayenne',
    'Seltzer with Lime',
    'Iced Black Tea (Mint)',
    'White Tea',
    'Guayusa Tea',
    'Rooibos Tea (Iced)',
    'Smoothie (Carrot, Apple, Ginger)',
    'Decaf Coffee',
    'Celery Juice',
    'Ginger Beer (Low Sugar)',
    'Fresh Orange Juice',
    'Unsweetened Cranberry Juice',
    'Fennel Tea',
    'Herbal Energy Drink',
    'Water with Himalayan Salt',
    'Lemonade (Sugar-Free)',
    'Vitamin Water (Zero Calorie)',
    'Almond Milk (Unsweetened)',
    'Iced Green Tea (Lemon)',
    'Vegetable Broth',
    'Pomegranate Juice',
    'Kaffir Lime Leaf Tea',
    'Licorice Root Tea',
    'Canned Sardines',
    'Tuna Pouch',
    'Veggies & Hummus Cup',
    'String Cheese',
    'Yogurt Drink',
    'Pre-cut Fruit Bowl',
    'Hard Boiled Eggs (Peeled)',
    'Single-Serve Nuts/Seeds',
    'Jerky (Beef or Turkey)',
    'Peanut Butter Cracker Sandwiches',
    'Granola Bar (High Protein)',
    'Trail Mix (Pre-packaged)',
    'Small Apple and Cheese Stick',
    'Pouch of Olives',
    'Mini Bagel with Cream Cheese',
    'Individual Guacamole Cup',
    'Canned Soup (Microwavable)',
    'Instant Oatmeal Cups',
    'Protein Bar',
    'Rice Cakes with Nut Butter',
    'Dried Edamame',
    'Canned Beans (Rinsed)',
    'Fruit Leather (100% Fruit)',
    'Canned Chili',
    'Individual Tuna Cans',
    'Pouch of Salmon',
    'Cereal Box (Mini)',
    'Frozen Waffles (Toasted)',
    'Instant Noodles (Cup)',
    'Microwave Popcorn (Plain)',
    'Yogurt Tube',
    'Pudding Cup (Protein)',
    'A Single Piece of Cheese',
    'Dried Mango Slices',
    'Hard Candy (Non-Sugary)',
    'Single-Serve Pretzels',
    'Mini Raisin Box',
    'Cereal Bar',
    'Mini Loaf of Banana Bread',
    'Apple Sauce Pouch',
    'Pistachios (Shelled)',
    'Canned Pickled Beets',
    'Individual Cottage Cheese Cup',
    'Mini Can of Tomato Soup',
    'Microwave Egg Bites',
    'Single-Serve Rice Pudding',
    'Baby Carrots (Bagged)',
    'Protein Cookie',
    'Mini Pack of Goldfish',
    'Dried Apricots',
  ],

  celebratory: [
    'Filet Mignon',
    'Lobster Thermidor',
    'Truffle Pasta',
    'Prime Rib Roast',
    'Caviar Blinis',
    'Lamb Shank',
    'Wagyu Beef',
    'Scallop Ceviche',
    'Grilled Rack of Lamb',
    'Duck Confit',
    'Foie Gras',
    'Seafood Paella',
    'Oysters on the Half Shell',
    'Chateaubriand',
    'Ahi Tuna Tartare',
    'Beef Wellington',
    'Peking Duck',
    'Agnolotti with Sage Butter',
    'King Crab Legs',
    'Black Cod with Miso',
    'Osso Buco',
    'Surf and Turf',
    'Veal Chop',
    'Dom Pérignon Champagne',
    'Aged Balsamic Vinegar',
    'Seared Foie Gras',
    'Truffle Fries',
    'Wagyu Tataki',
    'Spiny Lobster Tail',
    'Escargots in Garlic Butter',
    'Bouillabaisse',
    'Kobe Beef',
    'Truffle Pizza',
    'Roasted Quail',
    'Turbot (Whole Roasted)',
    'Dover Sole Meunière',
    'Uni (Sea Urchin)',
    'Saffron Risotto',
    'Grilled Octopus',
    'Rabbit Terrine',
    'Wild Boar Ragu',
    'Venison Loin',
    'Roasted Pheasant',
    'Bluefin Tuna Sashimi',
    'Langoustine',
    'Morel Mushroom Sauce',
    'Kurobuta Pork',
    'Calamari Steak',
    'Gnocchi with Duck Ragout',
    'Iberico Ham',
    'Zinfandel Wine',
    'Chardonnay (Oaked)',
    'Cognac (VSOP)',
    'Single Malt Scotch',
    'Dry Aged Ribeye',
    'Poussin (Roasted)',
    'Marrow Bone Soup',
    'Ratte Potatoes',
    'White Asparagus',
    'Fiddlehead Ferns',
    'Sautéed Chanterelles',
    'Heirloom Tomato Salad',
    'Artichokes a la Barigoule',
    'A5 Wagyu Nigiri',
    'Jamon Ibérico',
    'Moussaka (Gourmet)',
    'Khao Phad Sapparot',
    'Chicken Kiev (Butter Filled)',
    'Bacon Wrapped Dates',
    'Burrata with Fig Jam',
    'Seafood Linguine',
    'Octopus Carpaccio',
    'Cajun Prawns',
    'Baked Brie with Honey',
    'Pistachio Crusted Salmon',
    'Black Truffle Mac and Cheese',
    'Polenta with Porcini Mushrooms',
    'Grilled Swordfish',
    'Seafood Gumbo (Premium)',
    'Cioppino',
    'Whole Roasted Snapper',
    'Jamon Serrano',
    'Aged Cheddar Scones',
    'Deviled Eggs with Dill',
    'Prosciutto-Wrapped Asparagus',
    'Roasted Bone Marrow',
    'Zabaglione',
    'Champagne Vinegar Dressing',
    'Osetra Caviar',
    'Poularde de Bresse',
    'Kagoshima Beef',
    'Alaskan King Salmon',
    'Perigord Truffle',
    'Hokkaido Scallops',
    'Padrón Peppers',
    'Zuppa di Pesce',
    'Abalone',
    'Fugu (Pufferfish)',
    'Kopi Luwak Coffee',
    'Chocolate Fondue',
    'Baked Alaska',
    'Crème Brûlée',
    'Decadent Chocolate Cake',
    'Aged Cheese Platter',
    'Espresso Martini',
    'Fancy Cocktails',
    'Sparkling Cider',
    'Red Wine (Bordeaux)',
    'White Truffle Ice Cream',
    'Gold Leaf Dessert',
    'Grand Marnier Soufflé',
    'Petits Fours',
    'Chocolate Dipped Figs',
    'Single-Origin Coffee',
    'Port Wine',
    'Sherry (Amontillado)',
    'Bourbon (Aged)',
    'Scotch (Peated)',
    'Vodka Martini (Shaken, not stirred)',
    'Old Fashioned Cocktail',
    'Sazerac Cocktail',
    'Champagne Sorbet',
    'Whisky Sour',
    'Irish Coffee (with Cream)',
    'Tequila Anejo',
    'Rum (Dark, Aged)',
    'Eiswein',
    'Late Harvest Wine',
    'Panna Cotta with Raspberry Coulis',
    'Black Forest Gateau',
    'Opera Cake',
    'Pistachio Torte',
    'Lemon Tart (Meringue)',
    'Chocolate Cigars',
    'Spiced Pear Tart',
    'Rosewater Macarons',
    'Mignardises',
    'Pecan Tart (Bourbon)',
    'Grand Marnier Chocolate',
    'Salted Caramel Lava Cake',
    'Truffle Oil Popcorn',
    'Premium Hot Chocolate',
    'Hot Toddy',
    'Aperol Spritz',
    'Daiquiri (Classic)',
    'Manhattan Cocktail',
    'Negroni',
    'Bellini (Peach)',
    'Sidecar Cocktail',
    'Gimlet (Lime)',
    'Mint Chip Milkshake (Gourmet)',
    'Truffle Honey',
    'Smoked Sea Salt Caramel',
    'Artisan Chocolate Bar',
    'Candied Violets',
    'Gold Flaked Brownie',
    'Kahlúa Coffee',
    'Baileys Irish Cream',
    'Frangelico Liqueur',
    'Limoncello',
    'Triple Sec Cocktail',
    'Kir Royale',
    'Prosecco',
    'Ice Wine',
    'Sauternes',
    'Ouzo (Aperitif)',
    'Absinthe',
    'Chartreuse',
    'Artisan Bread Basket',
    'Prosciutto Wrapped Melon',
    'Charcuterie Board (Exotic Meats)',
    'Fine Cheese Board (French)',
    'Edible Flowers Salad',
    'Sourdough Bread (Premium)',
    'Kouign-Amann',
    'Cronut',
    'Canelé de Bordeaux',
    'Pastel de Nata',
    'Mille-feuille',
    'Ravioli (Handmade)',
    'Pappardelle with Truffle Oil',
    'Hand-Pulled Noodles',
    'Miso-Glazed Eel',
    'Dragon Fruit Salad',
    'Rambutan',
    'Mangosteen',
    'Durian (Fresh)',
    'Star Anise Lamb',
    'Zaatar Bread',
    'Kimchi (Aged)',
    'Kefir Cheese',
    'Goat Cheese (Ash Rind)',
    'Blue Cheese (Roquefort)',
    'Smoked Paprika',
    'Spanish Marcona Almonds',
    'Premium Olive Oil Tasting',
    'Pistachio Butter',
    'Black Garlic',
    'Saffron Threads',
    'Vanilla Beans (Tahitian)',
    'Himalayan Pink Salt',
    'Shish Kebab (Lamb)',
    'Causa Rellena',
    'Halo-Halo',
    'Feijoada',
    'Lutefisk',
    'Haggis',
    'Zongzi (Sticky Rice)',
    'Sushi & Sashimi Platter (Omakase)',
    'Thai Green Curry (Seafood)',
    'Dim Sum (Premium Selection)',
    'Tandoori Platter (Mixed Grill)',
    'Mole Poblano (Chicken)',
    'Brazilian Rodizio',
    'Peruvian Pollo a la Brasa',
    'Ethiopian Injera with Wat',
    'Korean Galbi (Short Ribs)',
    'Greek Moussaka',
    'Vietnamese Bún Chả',
    'Jollof Rice with Goat Meat',
    'Italian Antipasto Platter',
    'Spanish Tapas Assortment',
    'Moroccan Tagine (Lamb)',
    'Japanese Kaiseki Course',
    'Indian Biryani (Goat)',
    'Argentinian Asado',
    'Cochinita Pibil',
    'Goulash (Hungarian)',
    'Jamaican Jerk Chicken',
    'Peruvian Lomo Saltado',
    'Arepas Reina Pepiada',
    'Feijoada Completa',
    'Ceviche Mixto',
    'Pad Kra Pao (Basil Stir Fry)',
    'Pho Dac Biet (Special)',
    'Tom Yum Goong (Prawn Soup)',
    'Singapore Chili Crab',
    'Laksa (Curry Noodle Soup)',
    'Eel Nigiri',
    'Wagyu Ramen',
    'Banh Xeo (Crispy Pancake)',
    'Halo-Halo (Deluxe)',
    'Samosa Chaat',
    'Butter Naan (Garlic)',
    'Tikin Xic Fish',
    'Tlayudas',
    'Chapulines (Gourmet)',
    'Ginataang Manok',
  ],
};

const foodsToSeed: NewFood[] = [];
let foodId = 0;

MOOD_LIST.forEach((mood: Mood) => {
  const foodNames = FOOD_DATA[mood];
  foodNames.forEach((name) => {
    if (foodsToSeed.length <= 1000) {
      foodsToSeed.push({
        id: Bun.randomUUIDv7(),
        name: name.trim(),
        mood: mood,
        isAvailable: true,
      });
      foodId++;
    }
  });
});

export async function seedFoods(tx: DBTransaction) {
  try {
    console.log('🌱 Seeding foods...');

    await tx.insert(foods).values(foodsToSeed).onConflictDoNothing({
      target: foods.name,
    });

    console.log(`✅ ${foodsToSeed.length} foods seeded successfully`);
  } catch (error) {
    console.error('❌ Error seeding foods:', error);
    throw error;
  }
}
